{{- range $grp_key, $grp_val := .Values.resources }}
{{- range $res_key, $res_val := $grp_val.resources }}
apiVersion: {{ $res_val.apiVersion }}
kind: {{ $res_val.kind }}
metadata:
  name: {{ include "wrapper.fullname" $ }}-{{ $res_val.metadata.name }}
  {{- if and ($res_val.metadata) ($res_val.metadata.namespace) }}
  namespace: {{ $res_val.metadata.namespace }}
  {{- else if $grp_val.namespace }}
  namespace: {{ $grp_val.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- if or (and ($grp_val.metadata) ($grp_val.metadata.labels)) (and ($res_val.metadata) ($res_val.metadata.labels)) }}
  labels:
    {{- if and ($grp_val.metadata) ($grp_val.metadata.labels) }}
    {{- $grp_val.metadata.labels | toYaml | nindent 4 }}
    {{- end }}
    {{- if and ($res_val.metadata) ($res_val.metadata.labels) }}
    {{- $res_val.metadata.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or (and ($grp_val.metadata) ($grp_val.metadata.annotations)) (and ($res_val.metadata) ($res_val.metadata.annotations)) }}
  annotations:
    {{- if and ($grp_val.metadata) ($grp_val.metadata.annotations) }}
    {{- $grp_val.metadata.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if and ($res_val.metadata) ($res_val.metadata.annotations) }}
    {{- $res_val.metadata.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- if $res_val.spec }}
spec:
  {{- with $res_val.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- else }}
spec: { }
{{- end }}
{{- end }}
{{- end }}
