nameOverride: ""
fullnameOverride: ""

resources:
  - metadata:
      namespace: ""
      labels: { }
      annotations: { }
    resources:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx
          #namespace: ""
          #labels: { }
          #annotations: { }
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: nginx:1.14.2
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: config
        data:
          player_initial_lives: "3"
          ui_properties_file_name: "user-interface.properties"
          game.properties: |
            enemy.types=aliens,monsters
            player.maximum-lives=5
          user-interface.properties: |
            color.good=purple
            color.bad=yellow
            allow.textmode=true
      - apiVersion: v1
        kind: Secret
        metadata:
          name: string-data
        type: kubernetes.io/ssh-auth
        stringData:
          ssh-privatekey: |
            -----BEGIN OPENSSH PRIVATE KEY-----
      - apiVersion: v1
        kind: Secret
        metadata:
          name: data
        type: kubernetes.io/ssh-auth
        data:
          ssh-privatekey: |
            UG91cmluZzYlRW1vdGljb24lU2N1YmE=
