{{- if and .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch-stack.fullname" $ }}-self-ca
spec:
  commonName: CA
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "opensearch-stack.fullname" $ }}-self-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  duration: 2160h
  renewBefore: 360h
  secretName: {{ include "opensearch-stack.fullname" $ }}-self-ca-tls
---
{{- range $cert := .Values.certManager.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch-stack.fullname" $ }}-self-{{ $cert.name }}
spec:
  commonName: {{ $cert.name }}
  dnsNames: [ opensearch-master, opensearch-data ]
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "opensearch-stack.fullname" $ }}-self-leaf
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  duration: 720h
  renewBefore: 120h
  secretName: {{ include "opensearch-stack.fullname" $ }}-self-{{ $cert.name }}-tls
---
{{- end }}
{{- end }}