{{ if .Values.securityConfig.create }}
{{- $securityConfig := printf "%s/%s/%s" "files" "security-config" .Values.securityConfig.env  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch-stack.fullname" . }}-security-config
  labels:
    {{- include "opensearch-stack.labels" . | nindent 4 }}
data:
  action_groups.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "action_groups.yml") | b64enc }}
  config.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "config.yml") | b64enc }}
  internal_users.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "internal_users.yml") | b64enc }}
  roles.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "roles.yml") | b64enc }}
  roles_mapping.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "roles_mapping.yml") | b64enc }}
  tenants.yml: {{ .Files.Get (printf "%s/%s" $securityConfig "tenants.yml") | b64enc }}
{{- end }}