{{- if .Values.tlsTerminator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensearch-stack.fullname" . }}-tls-terminator
  labels:
    {{- include "opensearch-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls-terminator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opensearch-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tls-terminator
  template:
    metadata:
      labels:
        {{- include "opensearch-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tls-terminator
    spec:
      serviceAccountName: {{ include "opensearch-stack.fullname" . }}-tls-terminator
      automountServiceAccountToken: {{ .Values.tlsTerminator.serviceAccount.automount }}
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: config
              subPath: default.conf
            - mountPath: /usr/share/nginx/html/index.html
              name: config
              subPath: index.html
      terminationGracePeriodSeconds: 1
      volumes:
        - configMap:
            name: {{ include "opensearch-stack.fullname" . }}-tls-terminator
          name: config
{{- end }}