{{- if and .Values.tlsTerminator.enabled .Values.tlsTerminator.openshiftScc }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:openshift:scc:anyuid:{{ $.Release.Namespace }}:{{ include "opensearch-stack.fullname" . }}-tls-terminator"
subjects:
  - kind: ServiceAccount
    name: {{ include "opensearch-stack.fullname" . }}-tls-terminator
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
{{- end }}